(()=>{
  const work=document.getElementById('work');
  if(!work)return;

  const style=document.createElement('style');
  style.textContent=`
  .cases-note strong{color:#fff;font-weight:700}.cases-note span{color:#7f7f87}.cases-note{gap:11px}
  .case-zaisun{background:#cbb69e;min-height:720px;position:relative}.case-zaisun .zai-visual{position:absolute;inset:0;background:
    radial-gradient(circle at 78% 30%,rgba(255,255,255,.62) 0 7%,transparent 8%),
    linear-gradient(135deg,#e9d7c4 0%,#ceb195 43%,#9f785e 100%);overflow:hidden}
  .case-zaisun .zai-visual:before{content:"";position:absolute;width:34%;height:74%;right:13%;bottom:-8%;border-radius:44% 44% 28% 28%;background:linear-gradient(180deg,#f1e2d3,#cfae92);box-shadow:0 -38px 0 -24px rgba(255,255,255,.7)}
  .case-zaisun .zai-visual:after{content:"";position:absolute;width:24%;height:40%;right:18%;top:20%;border-radius:48% 48% 42% 42%;background:linear-gradient(180deg,#8b664e,#5b4031);filter:blur(.2px)}
  .case-zaisun:after{background:linear-gradient(90deg,rgba(10,10,12,.88) 0%,rgba(10,10,12,.42) 48%,rgba(10,10,12,.08) 75%),linear-gradient(to top,rgba(0,0,0,.7),transparent 58%)}
  .case-zaisun .case-meta{color:#fff}.real-badge{display:inline-flex;align-items:center;gap:8px}.real-badge i{width:7px;height:7px;border-radius:50%;background:var(--acid);box-shadow:0 0 0 5px rgba(217,255,63,.12)}
  .zai-brandplate{position:absolute;z-index:2;right:30px;top:74px;display:flex;flex-direction:column;align-items:flex-end;color:#fff;text-align:right}.zai-brandplate span{font:700 clamp(34px,4.2vw,62px)/.92 "Manrope";letter-spacing:-.07em}.zai-brandplate small{margin-top:7px;font-size:10px;letter-spacing:.13em;text-transform:uppercase;opacity:.78}
  .case-title-stack{display:flex;flex-direction:column;align-items:flex-start}.case-title-stack .project-label{display:inline-flex;margin-bottom:14px;padding:8px 11px;border:1px solid rgba(255,255,255,.25);border-radius:999px;font-size:9px;letter-spacing:.12em;text-transform:uppercase;color:#fff;background:rgba(0,0,0,.18);backdrop-filter:blur(8px)}
  .case-zaisun .case-title-stack h3{font-size:clamp(62px,9vw,132px);line-height:.78}.case-title-stack strong{margin-top:14px;font-size:15px;letter-spacing:-.02em;color:#fff}.case-zaisun .case-bottom p{max-width:360px}
  .case-live-link{display:inline-flex;margin-top:20px;padding:11px 15px;border-radius:999px;background:#111;color:#fff;font-size:10px;font-weight:700;letter-spacing:.08em;text-transform:uppercase;transition:.2s}.case-live-link:hover{background:var(--acid);color:#111}
  .mock-zaisun{background:#f4eadf;color:#332a24}.mock-zaisun .mock-inner{background:linear-gradient(180deg,#f7eee4 0%,#f2e6d8 100%)}.mock-zaisun .mock-nav{font-family:"Manrope"}.mock-zaisun .mock-kicker{color:#9a725a}.mock-zaisun .mock-btn{background:#d7a07f;color:#fff}.mock-zaisun .mock-product{background:#fff8f0;border:1px solid rgba(78,52,34,.09)}.mock-zaisun .mock-product .ph{background:linear-gradient(150deg,#e2cbb4,#f8eee4)}
  .zai-hero-shell{display:grid;grid-template-columns:1.05fr .95fr;gap:22px;align-items:stretch}.zai-copy-card{display:flex;flex-direction:column;justify-content:center;padding:28px;border-radius:24px;background:#fff8f0}.zai-copy-card .zai-logo{font:700 36px/1 "Manrope";letter-spacing:-.06em;margin-bottom:24px}.zai-copy-card h3{margin:0;font:700 clamp(30px,4vw,56px)/.92 "Manrope";letter-spacing:-.06em}.zai-copy-card p{color:#725f52;font-size:12px;line-height:1.6;max-width:360px}.zai-photo-card{border-radius:24px;min-height:310px;background:linear-gradient(145deg,#c6a488,#f0dfce);position:relative;overflow:hidden}.zai-photo-card:before{content:"";position:absolute;width:58%;height:78%;right:12%;bottom:-12%;border-radius:46% 46% 28% 28%;background:linear-gradient(180deg,#f4e7d8,#d4b79e);box-shadow:0 -36px 0 -24px rgba(255,255,255,.6)}.zai-photo-card:after{content:"NEW / KIDSWEAR";position:absolute;left:18px;bottom:16px;font-size:9px;letter-spacing:.15em;color:#fff}
  .zai-catalog-head{display:flex;justify-content:space-between;align-items:end;gap:20px;margin:8px 0 20px}.zai-catalog-head h3{margin:0;font:700 44px/.95 "Manrope";letter-spacing:-.06em}.zai-chips{display:flex;gap:7px;flex-wrap:wrap}.zai-chips span{padding:8px 10px;border-radius:999px;background:#fff8f0;border:1px solid rgba(60,40,30,.08);font-size:9px}
  .zai-admin-shell{display:grid;grid-template-columns:.72fr 1.28fr;gap:16px;background:#f1eee8;border-radius:22px;padding:16px}.zai-admin-menu{background:#202126;color:#fff;border-radius:18px;padding:18px}.zai-admin-menu b{display:block;font-size:16px;margin-bottom:24px}.zai-admin-menu span{display:block;padding:10px 0;border-bottom:1px solid rgba(255,255,255,.1);font-size:10px;color:#c8c8ce}.zai-admin-main{background:#fff;border-radius:18px;padding:18px}.zai-admin-top{display:flex;justify-content:space-between;align-items:center;margin-bottom:16px}.zai-admin-top b{font-size:18px}.zai-add{padding:8px 10px;border-radius:999px;background:#111;color:#fff;font-size:9px}.zai-row{display:grid;grid-template-columns:46px 1fr auto;gap:10px;align-items:center;padding:10px 0;border-top:1px solid #eee}.zai-thumb{width:46px;height:46px;border-radius:10px;background:linear-gradient(145deg,#e5d1be,#f7eee6)}.zai-row b{font-size:10px}.zai-row small{font-size:8px;color:#8a8a8f}.zai-actions{font-size:9px;color:#666}
  @media(max-width:700px){.case-zaisun{min-height:620px}.zai-brandplate{right:18px;top:72px}.case-zaisun .case-bottom{display:block}.case-zaisun .case-bottom p{text-align:left;margin-top:16px}.zai-hero-shell,.zai-admin-shell{grid-template-columns:1fr}.zai-photo-card{min-height:190px}.zai-admin-menu{display:none}.case-title-stack strong{font-size:12px}}
  `;
  document.head.appendChild(style);

  const wrap=work.querySelector('.wrap');
  wrap.innerHTML=`
    <div class="section-head reveal on">
      <div><div class="kicker">03 / Роботи</div><h2 class="section-title">Сайти, які<br><em>працюють на бізнес.</em></h2></div>
      <p class="section-copy">ZaiSun — реальний e-commerce проєкт, який уже працює для бренду дитячого одягу. Нижче — ще два концепти, щоб показати підхід до різних типів бізнесу.</p>
    </div>
    <div class="cases-note reveal on"><strong>1 реальний проєкт</strong><span>+ 2 демонстраційні напрямки</span></div>
    <div class="casegrid">
      <article class="case case-zaisun wide has-open reveal on" data-v23-case="zaisun" role="button" tabindex="0" aria-label="Відкрити реальний проєкт ZaiSun">
        <div class="zai-visual" aria-hidden="true"></div>
        <div class="zai-brandplate"><span>ZAISUN</span><small>дитячий одяг ручної роботи</small></div>
        <div class="case-meta"><span class="real-badge"><i></i>Real project / E-commerce</span><span>LIVE · ZAISUN.COM.UA</span></div>
        <div class="case-bottom"><div class="case-title-stack"><span class="project-label">Власний проєкт</span><h3>ZAISUN</h3><strong>Інтернет-магазин дитячого одягу</strong></div><p>Каталог, пошук і фільтри, кошик, оформлення замовлення, онлайн-оплата та власна адмінпанель для керування товарами.</p></div>
        <span class="case-open">Відкрити ↗</span>
      </article>
      <article class="case has-open reveal on" data-v23-case="shop" role="button" tabindex="0" aria-label="Відкрити концепт інтернет-магазину"><img src="https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1800&q=86" alt="Ecommerce concept"><div class="case-meta"><span>Концепт / E-commerce</span><span>2026</span></div><div class="case-bottom"><h3>Інтернет-<br>магазин</h3><p>Каталог, зручне оформлення замовлення та структура, готова до реклами.</p></div><span class="case-open">Відкрити ↗</span></article>
      <article class="case has-open reveal on" data-v23-case="company" role="button" tabindex="0" aria-label="Відкрити концепт сайту для компанії"><img src="https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1800&q=86" alt="Corporate concept"><div class="case-meta"><span>Концепт / Сайт для бізнесу</span><span>2026</span></div><div class="case-bottom"><h3>Сайт для<br>компанії</h3><p>Пояснює послуги простими словами, показує переваги й веде клієнта до заявки.</p></div><span class="case-open">Відкрити ↗</span></article>
    </div>`;

  const data={
    zaisun:{eyebrow:'Реальний проєкт / E-commerce',title:'ZaiSun',lead:'Власний e-commerce проєкт для бренду дитячого одягу, який уже працює з реальними товарами та замовленнями.',task:'Перенести продажі бренду у повноцінний інтернет-магазин і зробити шлях від вибору товару до оформлення замовлення максимально простим.',done:'Каталог, пошук і фільтри, картки товарів, кошик, оформлення замовлення, онлайн-оплата, мобільна версія та власна адмінпанель.',focus:'Простий шлях покупця + керування асортиментом без роботи з кодом.',tech:'Кастомна розробка · власна адмінпанель · e-commerce логіка · інтеграції',url:'zaisun.com.ua',live:'https://zaisun.com.ua',tabs:['Головна','Каталог','Адмінка'],benefits:['Реальний сайт у роботі','Каталог, пошук і фільтри','Кошик та оформлення замовлення','Онлайн-оплата','Мобільна версія','Керування товарами з власної адмінпанелі']},
    shop:{eyebrow:'Демонстраційний концепт / E-commerce',title:'Інтернет-магазин',lead:'Демонстрація e-commerce підходу: від першого екрану до каталогу й оформлення замовлення.',task:'Зробити магазин, де товар легко знайти, зрозуміти й купити без зайвих кроків.',done:'Структура каталогу, картка товару, кошик, CTA, мобільна логіка та підготовка до реклами.',focus:'Швидкий шлях від реклами до товару й замовлення.',tech:'HTML / CSS / JS · CMS або e-commerce платформа · GA4 · Merchant Center',url:'shop.shift.preview',tabs:['Головна','Внутрішня','Mobile / CTA'],benefits:['Продумана структура каталогу','Адаптивна мобільна версія','Кошик і сценарій покупки','Базова аналітика','Підготовка до Google Shopping','Зрозуміле керування контентом']},
    company:{eyebrow:'Демонстраційний концепт / Business site',title:'Сайт для компанії',lead:'Сайт, який швидко пояснює, хто ви, що робите й чому клієнту варто звернутися саме до вас.',task:'Упакувати послуги компанії у зрозумілу структуру та вести від першого екрану до заявки.',done:'Головна, послуги, приклади робіт, процес роботи, блоки довіри, форми та адаптив.',focus:'Довіра, зрозуміла подача послуг і заявка.',tech:'HTML / CSS / JS · CMS · GA4 · форми та інтеграції',url:'company.shift.preview',tabs:['Головна','Внутрішня','Mobile / CTA'],benefits:['Індивідуальна структура','Сторінки послуг','Блоки довіри','Форми звернення','Адаптив під мобільні','Підготовка до реклами']}
  };

  const modal=document.getElementById('caseModal');
  const viewport=document.getElementById('mockViewport');
  const tabs=[...document.querySelectorAll('.mock-tab')];
  const genericScreens=(theme)=>[
    `<section class="mock-page active"><div class="mock-inner"><div class="mock-nav"><span>SHIFT / ${theme.toUpperCase()}</span><small>Меню&nbsp;&nbsp; Контакти</small></div><div class="mock-hero-grid"><div><div class="mock-kicker">Нова digital-подача</div><h3 class="mock-title">Сайт, який веде до дії.</h3><p class="mock-copy">Чітка структура, сильний перший екран і зрозумілий наступний крок для клієнта.</p><span class="mock-btn">Обрати / Замовити ↗</span></div><div class="mock-art"></div></div></div></section>`,
    `<section class="mock-page"><div class="mock-inner"><div class="mock-nav"><span>SHIFT / DETAIL</span><small>Назад&nbsp;&nbsp; CTA</small></div><div class="mock-kicker">Внутрішня сторінка</div><h3 class="mock-title">Менше шуму.<br>Більше ясності.</h3><p class="mock-copy">Детальна сторінка розкладає пропозицію на переваги, процес, докази й конкретну дію.</p></div></section>`,
    `<section class="mock-page"><div class="mock-inner" style="max-width:430px;margin:auto"><div class="mock-nav"><span>SHIFT / MOBILE</span><small>☰</small></div><div class="mock-art" style="min-height:190px;margin-bottom:20px"></div><div class="mock-kicker">Mobile first</div><h3 class="mock-title">Зручно з телефону.</h3><p class="mock-copy">Великі кнопки, короткі блоки, швидкий контакт і мінімум зайвих кроків.</p></div></section>`
  ].join('');
  const zaisunScreens=()=>[
    `<section class="mock-page active mock-zaisun"><div class="mock-inner"><div class="mock-nav"><span>ZaiSun</span><small>Каталог&nbsp;&nbsp; Доставка&nbsp;&nbsp; Кошик</small></div><div class="zai-hero-shell"><div class="zai-copy-card"><div class="zai-logo">ZaiSun</div><div class="mock-kicker">Дитячий одяг ручної роботи</div><h3>Одяг, у якому дитині зручно.</h3><p>М'яка подача бренду, зрозумілий каталог і швидкий перехід до покупки.</p><span class="mock-btn">Перейти в каталог ↗</span></div><div class="zai-photo-card"></div></div><div class="mock-products"><div class="mock-product"><div class="ph"></div><b>Категорії</b><small>Зручна навігація</small></div><div class="mock-product"><div class="ph"></div><b>Новинки</b><small>Швидкий доступ до товарів</small></div><div class="mock-product"><div class="ph"></div><b>Переваги</b><small>Довіра до бренду</small></div></div></div></section>`,
    `<section class="mock-page mock-zaisun"><div class="mock-inner"><div class="mock-nav"><span>ZaiSun / Каталог</span><small>Пошук&nbsp;&nbsp; Кошик</small></div><div class="zai-catalog-head"><div><div class="mock-kicker">Каталог</div><h3>Обрати легко.</h3></div><div class="zai-chips"><span>Новинки</span><span>Комбінезони</span><span>Боді</span><span>Комплекти</span></div></div><div class="mock-products"><div class="mock-product"><div class="ph"></div><b>Товар 01</b><small>Розмір · колір · ціна</small></div><div class="mock-product"><div class="ph"></div><b>Товар 02</b><small>Розмір · колір · ціна</small></div><div class="mock-product"><div class="ph"></div><b>Товар 03</b><small>Розмір · колір · ціна</small></div></div></div></section>`,
    `<section class="mock-page mock-zaisun"><div class="mock-inner"><div class="mock-nav"><span>ZaiSun / Admin</span><small>Вхід виконано</small></div><div class="mock-kicker">Власна система керування</div><h3 class="mock-title" style="max-width:760px">Товари можна змінювати без коду.</h3><p class="mock-copy">Адміністратор додає, редагує або прибирає товари та керує асортиментом із телефону чи комп'ютера.</p><div class="zai-admin-shell"><div class="zai-admin-menu"><b>ZaiSun Admin</b><span>Товари</span><span>Категорії</span><span>Замовлення</span><span>Налаштування</span></div><div class="zai-admin-main"><div class="zai-admin-top"><b>Товари</b><span class="zai-add">+ Додати товар</span></div><div class="zai-row"><div class="zai-thumb"></div><div><b>Комплект дитячий</b><br><small>Активний · в наявності</small></div><span class="zai-actions">Редагувати</span></div><div class="zai-row"><div class="zai-thumb"></div><div><b>Комбінезон</b><br><small>Активний · 4 розміри</small></div><span class="zai-actions">Редагувати</span></div></div></div></div></section>`
  ].join('');

  function setScreen(i){document.querySelectorAll('.mock-page').forEach((p,n)=>p.classList.toggle('active',n===i));tabs.forEach((b,n)=>b.classList.toggle('active',n===i));}
  function open(key){const d=data[key];if(!d||!modal)return;document.getElementById('caseEyebrow').textContent=d.eyebrow;document.getElementById('caseTitle').textContent=d.title;document.getElementById('caseLead').textContent=d.lead;document.getElementById('caseTask').textContent=d.task;document.getElementById('caseDone').textContent=d.done;document.getElementById('caseFocus').textContent=d.focus;document.getElementById('caseTech').textContent=d.tech;document.getElementById('mockUrl').textContent=d.url;document.getElementById('caseBenefits').innerHTML=d.benefits.map(x=>`<li>${x}</li>`).join('');let live=document.getElementById('caseLive');if(!live){live=document.createElement('a');live.id='caseLive';live.className='case-live-link';document.getElementById('caseTitle').after(live)}if(d.live){live.href=d.live;live.target='_blank';live.rel='noopener';live.textContent='Відкрити живий сайт ↗';live.style.display='inline-flex'}else{live.style.display='none'}tabs.forEach((b,i)=>b.textContent=d.tabs[i]);viewport.innerHTML=key==='zaisun'?zaisunScreens():genericScreens(key);setScreen(0);modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}

  work.querySelectorAll('[data-v23-case]').forEach(el=>{el.addEventListener('click',()=>open(el.dataset.v23Case));el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open(el.dataset.v23Case)}})});
  tabs.forEach((b,i)=>b.addEventListener('click',()=>setScreen(i)));
})();
